### ISSUE TITLE
输入图片数据不能转化

### ISSUE THREAD

**Issue by sijie-Xu** [cclamd/MobileSAM-Adapter#1]
![1150bdc3694a4c43b32accbc3a13fa9](https://github.com/cclamd/MobileSAM-Adapter/assets/122505422/12dad4d7-7b71-45af-9cf4-2af599e8fa25)
这是我输入的参数配置，除了预训练模型改成mobile sam,其他按照sam-adapter的配置
然后在dataset.py中将文件修改成
![image](https://github.com/cclamd/MobileSAM-Adapter/assets/122505422/cd570b1b-7a68-4d18-b7db-a30c073f51c8)
然后根据原文件修改成255
![image](https://github.com/cclamd/MobileSAM-Adapter/assets/122505422/35d58def-4413-45e5-a963-b488d9dc3070)

但是还是出错了，请问这是什么问题，我看代码中取消了缩放为1024尺寸，是不是这里有问题
![image](https://github.com/cclamd/MobileSAM-Adapter/assets/122505422/95aa9052-6bfb-4156-ba00-a0276681bbf8)

**Comment by DONGGUANLIANG** [comment]
> ![1150bdc3694a4c43b32accbc3a13fa9](https://private-user-images.githubusercontent.com/122505422/285369492-12dad4d7-7b71-45af-9cf4-2af599e8fa25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzY5NDkyLTEyZGFkNGQ3LTdiNzEtNDVhZi05Y2Y0LTJhZjU5OWU4ZmEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzMzY2VkZDhmYWYxMTcwNjMzOWI2NDk0ZTZiNjZkYWQ5ZDdlZWU5NGUxYmFmNDY1OTZlZTMzYmJjMzhmOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6lkoQsggPMz3kC7nSP45TiL9feILqGRpKnHcowLIL8M) 这是我输入的参数配置，除了预训练模型改成mobile sam，其他按照sam-adapter的配置 然后在dataset.py中修改文件成 然后根据原文件修改成255 ![图像](https://private-user-images.githubusercontent.com/122505422/285370121-cd570b1b-7a68-4d18-b7db-a30c073f51c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzcwMTIxLWNkNTcwYjFiLTdhNjgtNGQxOC1iN2RiLWEzMGMwNzNmNTFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTcwODA0ZTYzMWIwZDM0OTBmMDdkYzFiNDRhODc3NDczNDFlNTRkOTBhYjljMGNjZDg2YmEyMGQxYTlhMmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KJAXxctOLSFoLy-ssjQ2dzxoHQPOza1oxU3J_31n4xI) ![图像](https://private-user-images.githubusercontent.com/122505422/285370158-35d58def-4413-45e5-a963-b488d9dc3070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzcwMTU4LTM1ZDU4ZGVmLTQ0MTMtNDVlNS1hOTYzLWI0ODhkOWRjMzA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWQ0NmExZjVlYzk1NDVlOTZjYTNkZTQyNTEyMTEzZTBkNjU5ZmVhNWU0ZjJhYzQyOWNiMWUxZWNmNDY5NWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OVus5QFsYwklKZRajScSg2esIFpO2wqtBg4VrGRB358)
> 
> 但是还是出错了，请问这是什么问题，我看代码中取消了缩放为1024尺寸，是不是这里有问题 ![图像](https://private-user-images.githubusercontent.com/122505422/285370292-95aa9052-6bfb-4156-ba00-a0276681bbf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzcwMjkyLTk1YWE5MDUyLTZiZmItNDE1Ni1iYTAwLWEwMjc2NjgxYmJmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2QyODAxOGQ1OWVhNTE4MmIzNDA3OWI4MTY3ZTAwNjA4NWNjNTE3NDc4YzQwZTVjYTBmOGRjZjk2OTdmMjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UOcLUB2EpKfJrIMwkC7N-UZsLsKM1a8Rfu5dDelbrIM)

请问你跑成功了吗

**Comment by sijie-Xu** [comment]
> > ![1150bdc3694a4c43b32accbc3a13fa9](https://private-user-images.githubusercontent.com/122505422/285369492-12dad4d7-7b71-45af-9cf4-2af599e8fa25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzY5NDkyLTEyZGFkNGQ3LTdiNzEtNDVhZi05Y2Y0LTJhZjU5OWU4ZmEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzMzY2VkZDhmYWYxMTcwNjMzOWI2NDk0ZTZiNjZkYWQ5ZDdlZWU5NGUxYmFmNDY1OTZlZTMzYmJjMzhmOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6lkoQsggPMz3kC7nSP45TiL9feILqGRpKnHcowLIL8M) 这是我输入的参数配置，除了预训练模型改成mobile sam，其他按照sam-adapter的配置 然后在dataset.py中修改文件成 然后根据原文件修改成255 ![图像](https://private-user-images.githubusercontent.com/122505422/285370121-cd570b1b-7a68-4d18-b7db-a30c073f51c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzcwMTIxLWNkNTcwYjFiLTdhNjgtNGQxOC1iN2RiLWEzMGMwNzNmNTFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTcwODA0ZTYzMWIwZDM0OTBmMDdkYzFiNDRhODc3NDczNDFlNTRkOTBhYjljMGNjZDg2YmEyMGQxYTlhMmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KJAXxctOLSFoLy-ssjQ2dzxoHQPOza1oxU3J_31n4xI) ![图像](https://private-user-images.githubusercontent.com/122505422/285370158-35d58def-4413-45e5-a963-b488d9dc3070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzcwMTU4LTM1ZDU4ZGVmLTQ0MTMtNDVlNS1hOTYzLWI0ODhkOWRjMzA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWQ0NmExZjVlYzk1NDVlOTZjYTNkZTQyNTEyMTEzZTBkNjU5ZmVhNWU0ZjJhYzQyOWNiMWUxZWNmNDY5NWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OVus5QFsYwklKZRajScSg2esIFpO2wqtBg4VrGRB358)
> > 但是还是出错了，请问这是什么问题，我看代码中取消了缩放为1024尺寸，是不是这里有问题 ![图像](https://private-user-images.githubusercontent.com/122505422/285370292-95aa9052-6bfb-4156-ba00-a0276681bbf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjYzNDksIm5iZiI6MTcwNDcyNjA0OSwicGF0aCI6Ii8xMjI1MDU0MjIvMjg1MzcwMjkyLTk1YWE5MDUyLTZiZmItNDE1Ni1iYTAwLWEwMjc2NjgxYmJmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2QyODAxOGQ1OWVhNTE4MmIzNDA3OWI4MTY3ZTAwNjA4NWNjNTE3NDc4YzQwZTVjYTBmOGRjZjk2OTdmMjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UOcLUB2EpKfJrIMwkC7N-UZsLsKM1a8Rfu5dDelbrIM)
> 
> 请问你跑成功了吗

没有，我放弃了

**Comment by cclamd** [comment]
hi  , the project  have been moved to [https://github.com/KidsWithTokens/Medical-SAM-Adapter](url)

thanks!
